# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6085b9f3cb96b6ffce7c18b5a2872f1d0785f7734f2d7a0d9e7ca091b7aa7a905890d600a5689f2faf9159a7be0b438d9adedb52982159e42d669728db21166

test:
  secret_key_base: 1c3966fede51b2009b7a5dc1e18a3148fd4007810568eba9b0775a005ca70fa1e9c7a596f2fdf230383c275a06a9670c5472e3f520fda184a302301de6304608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
